# Generated by Django 5.0.2 on 2024-02-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='largest_price',
            field=models.FloatField(default=models.FloatField(default=0)),
        ),
    ]
