# Generated by Django 5.0.2 on 2024-02-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_min_price_alter_listing_largest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.ImageField(default='auctions/images/default-placeholder.png', upload_to='auctions/images/'),
        ),
    ]
