# Generated by Django 5.0.2 on 2024-02-23 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 16, 7, 16, 498434)),
        ),
    ]
