# Generated by Django 5.0.2 on 2024-02-23 16:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='min_price',
            new_name='latest_bid_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='largest_price',
        ),
        migrations.AddField(
            model_name='listing',
            name='latest_bider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 18, 14, 41, 808762)),
        ),
    ]
