# Generated by Django 5.0.2 on 2024-02-23 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_min_price_listing_latest_bid_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchList',
            field=models.ManyToManyField(blank=True, related_name='user_watching', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 0, 49, 17, 880451)),
        ),
    ]
