# Generated by Django 5.0.2 on 2024-02-24 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_created_at_alter_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 22, 26, 14, 753059)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 22, 26, 14, 748532)),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('icon', models.ImageField(default='media/auctions/categoryIcons/category-base.png', upload_to='media/auctions/categoryIcons')),
                ('listings', models.ManyToManyField(related_name='categories', to='auctions.listing')),
            ],
        ),
    ]
